import { MenuItem } from "./types";

export const seedMenuItems: MenuItem[] = [
  // ===== SALADS =====
  {
    id: "greens-crumbs",
    name: "Greens & Crumbs",
    description: "Greens, breadcrumbs, parmesan, seeds, mustard vinaigrette",
    price: 10,
    category: "salads",
    available: true,
  },
  {
    id: "beetroot-salad",
    name: "Beetroot",
    description: "Greens, grilled beetroot, goat cheese, candied pecans, shanklish dressing",
    price: 12,
    category: "salads",
    available: true,
  },
  {
    id: "caesar-salad",
    name: "Caesar",
    description: "Sucrine, parmesan, croutons, bacon bits, caesar dressing. Add chicken $3",
    price: 12,
    category: "salads",
    available: true,
  },

  // ===== APPETIZERS =====
  {
    id: "focaccia",
    name: "Focaccia",
    description: "Olea's EVOO & tapenade",
    price: 7,
    category: "appetizers",
    available: true,
  },
  {
    id: "nachos",
    name: "Nachos",
    description: "Salsa, guac and bean spread",
    price: 10,
    category: "appetizers",
    available: true,
  },
  {
    id: "melanzane",
    name: "Melanzane",
    description: "Roasted eggplant, sundried tomato, parmesan, breadcrumbs",
    price: 10,
    category: "appetizers",
    available: true,
  },
  {
    id: "fries",
    name: "Fries",
    description: "With house dip",
    price: 6,
    category: "appetizers",
    available: true,
  },
  {
    id: "ribs",
    name: "Ribs",
    description: "Half rack, house BBQ sauce, fries",
    price: 22,
    category: "appetizers",
    available: true,
  },
  {
    id: "wings",
    name: "Wings",
    description: "With house glaze",
    price: 14,
    category: "appetizers",
    available: true,
  },

  // ===== TARTINES =====
  {
    id: "garlic-bread",
    name: "Garlic Bread",
    description: "Focaccia, roasted garlic paste, parmesan, herbes de Provence",
    price: 7,
    category: "tartines",
    available: true,
  },
  {
    id: "bruschetta",
    name: "Bruschetta",
    description: "Focaccia, roasted garlic paste, tomato, stracciatella, basil oil",
    price: 8,
    category: "tartines",
    available: true,
  },
  {
    id: "mushroom-toast",
    name: "Mushroom Toast",
    description: "Focaccia, confit mushrooms, thyme",
    price: 12,
    category: "tartines",
    available: true,
  },

  // ===== PIZZAS =====
  {
    id: "marinara",
    name: "Marinara",
    description: "Tomato, garlic, herbs",
    price: 10,
    category: "pizzas",
    available: true,
  },
  {
    id: "marguerita",
    name: "Marguerita",
    description: "Tomato, mozzarella, basil",
    price: 12,
    category: "pizzas",
    available: true,
  },
  {
    id: "siciliana",
    name: "Siciliana",
    description: "Tomato, mozzarella, goat cheese, sundried tomatoes, spinach",
    price: 16,
    category: "pizzas",
    available: true,
  },
  {
    id: "regina",
    name: "Regina",
    description: "Tomato, mozzarella, ham, mushroom",
    price: 16,
    category: "pizzas",
    available: true,
  },
  {
    id: "diavola",
    name: "Diavola",
    description: "Tomato, mozzarella, chorizo",
    price: 16,
    category: "pizzas",
    available: true,
  },
  {
    id: "breasaola",
    name: "Breasaola",
    description: "Tomato, mozzarella, bresaola, arugula",
    price: 18,
    category: "pizzas",
    available: true,
  },

  // ===== SANDWICHES =====
  {
    id: "veggie-sandwich",
    name: "Veggie",
    description: "Eggplant, zucchini, onion, mushroom, goat cheese, spinach, black pepper oil, ciabatta",
    price: 10,
    category: "sandwiches",
    available: true,
  },
  {
    id: "frank",
    name: "Frank",
    description: "Blackcap sausage, yellow mustard, brioche bun",
    price: 8,
    category: "sandwiches",
    available: true,
  },
  {
    id: "italian-sandwich",
    name: "Italian",
    description: "Ham, chorizo, mozzarella, mushroom, onion, sundried tomato dip, arugula, basil oil, ciabatta",
    price: 15,
    category: "sandwiches",
    available: true,
  },
  {
    id: "chicken-club",
    name: "Chicken Club",
    description: "Chicken, boiled egg, ham, emmental, tomato, lettuce, house mayo, mustard, cornichon, pain de mie, fries. Add bacon $3",
    price: 16,
    category: "sandwiches",
    available: true,
  },

  // ===== PLATTERS =====
  {
    id: "fish-chips",
    name: "Fish & Chips",
    description: "Beer-battered local fish, fries, curry sauce",
    price: 20,
    category: "platters",
    available: true,
  },
  {
    id: "sunday-roast",
    name: "Sunday Roast",
    description: "Blackcap brisket, mashed potatoes, house gravy",
    price: 25,
    category: "platters",
    available: true,
  },

  // ===== DESSERTS =====
  {
    id: "tiramisu",
    name: "Tiramisu",
    description: "Classic Italian tiramisu",
    price: 12,
    category: "desserts",
    available: true,
  },
  {
    id: "moelleux-chocolat",
    name: "Moelleux au Chocolat",
    description: "Warm chocolate fondant",
    price: 13,
    category: "desserts",
    available: true,
  },
  {
    id: "pain-perdu",
    name: "Pain Perdu",
    description: "French toast",
    price: 10,
    category: "desserts",
    available: true,
  },

  // ===== CLASSICS (Cocktails) =====
  {
    id: "gimlet",
    name: "Gimlet",
    description: "Gin, sugar, kaffir lime",
    price: 12,
    category: "classics",
    available: true,
  },
  {
    id: "daiquiri",
    name: "Daiquiri",
    description: "Rum, sugar, lime",
    price: 12,
    category: "classics",
    available: true,
  },
  {
    id: "margarita",
    name: "Margarita",
    description: "Tequila, agave, lime",
    price: 12,
    category: "classics",
    available: true,
  },
  {
    id: "negroni",
    name: "Negroni",
    description: "Gin, Campari, sweet vermouth",
    price: 12,
    category: "classics",
    available: true,
  },
  {
    id: "old-fashioned",
    name: "Old Fashioned",
    description: "Bourbon, sugar, bitters",
    price: 12,
    category: "classics",
    available: true,
  },
  {
    id: "whiskey-sour",
    name: "Whiskey Sour",
    description: "Bourbon, sugar, lemon, foam",
    price: 12,
    category: "classics",
    available: true,
  },
  {
    id: "mai-tai",
    name: "Mai Tai",
    description: "Aged rum mix, Cointreau, orgeat, sugar, lime",
    price: 14,
    category: "classics",
    available: true,
  },
  {
    id: "martini",
    name: "Martini",
    description: "Vodka or Gin, dry vermouth, bitters",
    price: 14,
    category: "classics",
    available: true,
  },

  // ===== HIGHBALL & FIZZES =====
  {
    id: "gin-tonic",
    name: "Gin & Tonic",
    description: "Gin, tonic",
    price: 10,
    category: "highball-fizzes",
    available: true,
  },
  {
    id: "whiskey-highball",
    name: "Whiskey Highball",
    description: "Whiskey, bubbles",
    price: 10,
    category: "highball-fizzes",
    available: true,
  },
  {
    id: "paloma",
    name: "Paloma",
    description: "Tequila, agave, grapefruit, lime, bubbles",
    price: 12,
    category: "highball-fizzes",
    available: true,
  },
  {
    id: "french-75",
    name: "French 75",
    description: "Gin, cognac, sugar, lemon, sparkling wine",
    price: 12,
    category: "highball-fizzes",
    available: true,
  },
  {
    id: "bloody-mary",
    name: "Bloody Mary",
    description: "Vodka, tomato juice, spices, lemon",
    price: 12,
    category: "highball-fizzes",
    available: true,
  },

  // ===== SPIRIT FORWARD =====
  {
    id: "boulevardier",
    name: "Boulevardier",
    description: "Rye whiskey, Campari, sweet vermouth",
    price: 14,
    category: "spirit-forward",
    available: true,
  },
  {
    id: "sazerac",
    name: "Sazerac",
    description: "Rye whiskey, cognac, sugar, Peychaud bitters, absinthe",
    price: 14,
    category: "spirit-forward",
    available: true,
  },
  {
    id: "vieux-carre",
    name: "Vieux Carré",
    description: "Rye whisky, cognac, sweet vermouth, Benedictine, bitters",
    price: 14,
    category: "spirit-forward",
    available: true,
  },

  // ===== WINE =====
  {
    id: "qanafar-viognier",
    name: "Qanafar, Viognier (White)",
    description: "Viognier — Glass $7 / Bottle $35",
    price: 7,
    category: "wine",
    subcategory: "White",
    available: true,
  },
  {
    id: "qanafar-petit-paradis",
    name: "Qanafar, Petit Paradis (Red)",
    description: "Syrah, Cabernet Sauvignon, Merlot — Glass $7 / Bottle $35",
    price: 7,
    category: "wine",
    subcategory: "Red",
    available: true,
  },
  {
    id: "couvent-rouge-petnat",
    name: "Couvent Rouge, Petnat (Bubbles)",
    description: "Sauvignon Blanc, Obeidi, Viognier, Muscat — Glass $7 / Bottle $35",
    price: 7,
    category: "wine",
    subcategory: "Bubbles",
    available: true,
  },

  // ===== BEERS & CIDERS =====
  {
    id: "elmir-pilsner",
    name: "Elmir Pilsner",
    description: "On Tap — Pint $8 / Half $4",
    price: 8,
    category: "beers-ciders",
    subcategory: "On Tap",
    available: true,
  },
  {
    id: "elmir-ipa",
    name: "Elmir IPA",
    description: "On Tap — Pint $8 / Half $4",
    price: 8,
    category: "beers-ciders",
    subcategory: "On Tap",
    available: true,
  },
  {
    id: "heineken",
    name: "Heineken",
    description: "Bottle",
    price: 6,
    category: "beers-ciders",
    subcategory: "Bottles",
    available: true,
  },
  {
    id: "elmir-wheat-ale",
    name: "Elmir Wheat Ale",
    description: "Bottle",
    price: 8,
    category: "beers-ciders",
    subcategory: "Bottles",
    available: true,
  },
];
